gtkmm 2.4: Gtk::Box_Helpers::Child Class Reference
Main Page Widgets Namespaces Book
Gtk::Box_Helpers::Child Class Reference
Public Member Functions
bool get_expand () const
bool get_fill () const
bool get_pack () const
guint16 get_padding () const
Widget* get_widget () const
const _GtkBoxChild* gobj () const
Provides access to the underlying C GObject.
_GtkBoxChild* gobj ()
Provides access to the underlying C GObject.
void set_options (bool expand, bool fill, guint padding=0)
void set_options (PackOptions options, guint padding=0)
void set_pack (PackType pack)
Protected Member Functions
GtkBox* parent ()
void redraw ()
Member Function Documentation
bool Gtk::Box_Helpers::Child::get_expand () const [inline]
References gobj().
bool Gtk::Box_Helpers::Child::get_fill () const [inline]
References gobj().
bool Gtk::Box_Helpers::Child::get_pack () const [inline]
References gobj().
guint16 Gtk::Box_Helpers::Child::get_padding () const [inline]
References gobj().
Widget* Gtk::Box_Helpers::Child::get_widget () const
const _GtkBoxChild* Gtk::Box_Helpers::Child::gobj () const [inline]
Provides access to the underlying C GObject.
_GtkBoxChild* Gtk::Box_Helpers::Child::gobj () [inline]
Provides access to the underlying C GObject.
Referenced by get_expand(), get_fill(), get_pack(), get_padding(), and parent().
GtkBox* Gtk::Box_Helpers::Child::parent () [inline, protected]
References gobj().
void Gtk::Box_Helpers::Child::redraw () [protected]
void Gtk::Box_Helpers::Child::set_options (bool expand, bool fill, guint padding = 0)
void Gtk::Box_Helpers::Child::set_options (PackOptions options, guint padding = 0)
void Gtk::Box_Helpers::Child::set_pack (PackType pack)
The documentation for this class was generated from the following file:
box.h
Generated for gtkmm 2.4 by Doxygen 1.5.8 © 1997-2001