gtkmm 2.4: Gtk Namespace Reference
Main Page Widgets Namespaces Book
Gtk Namespace Reference
Namespaces
namespace AccelMap
namespace Box_Helpers
namespace ComboDropDown_Helpers
namespace Menu_Helpers
namespace Notebook_Helpers
namespace Stock
namespace Table_Helpers
Classes
class AboutDialog
The AboutDialog offers a simple way to display information about a program like its logo, name, copyright, website and license.
class AccelGroup
A Gtk::AccelGroup represents a group of keyboard accelerators, typically attached to a toplevel Gtk::Window (with Gtk::Window::add_accel_group()).
class AccelKey
Defines accelerator key combinations.
class AccelLabel
A label which displays an accelerator key on the right of the text.
class Action
An action which can be triggered by a menu or toolbar item.
class ActionGroup
class Adjustment
A class representing an adjustable bounded value.
class Alignment
A widget which controls the alignment and size of its child.
class Arrow
Produces an arrow pointing in one of the four cardinal directions.
class AspectFrame
A frame that constrains its child to a particular aspect ratio.
class Assistant
A widget used to guide users through multi-step operations.
class Bin
A container with just one child.
class Box
A base class for box containers.
class Builder
Build an interface from a UI definition description.
class BuilderError
Exception class for Gdk::Builder errors.
struct BuiltinStockID
See the list of pre-defined stock items, in the Stock namespace.
class Button
A widget that creates a signal when clicked on.
class ButtonBox
Base class for Gtk::HButtonBox and Gtk::VButtonBox.
class Calendar
Display a calendar and/or allow the user to select a date.
class CellEditable
Interface for widgets which are used for editing cells.
class CellLayout
An interface for packing cells.
class CellRenderer
CellRenderers are used by Gtk::TreeView columns to render the Gtk::TreeModel column data appropriately.
class CellRendererAccel
Renders a keyboard accelerator in a cell
class CellRendererCombo
Renders a combobox in a cell.
class CellRendererPixbuf
Renders a pixbuf in a cell.
class CellRendererProgress
Renders numbers as progress bars.
class CellRendererSpin
Renders a spin button in a cell.
class CellRendererText
Renders text in a cell.
class CellRendererToggle
Renders a toggle button in a cell.
class CellView
A widget displaying a single row of a TreeModel.
class CheckButton
Create widgets with a discrete toggle button.
class CheckMenuItem
A menu item that maintains the state of a boolean value in addition to a Gtk::MenuItem's usual role in activating application code.
class Clipboard
The Clipboard object represents a clipboard of data shared between different processes or between different widgets in the same process.
class ColorButton
A button to launch a color selection dialog.
class ColorSelection
A widget used to select a color.
class ColorSelectionDialog
This dialog allows the user to select a color.
class Combo
A text entry field with a dropdown list.
class ComboBox
A widget used to choose from a list of items.
class ComboBoxEntry
A text entry field with a dropdown list.
class ComboBoxEntryText
This is a specialisation of the ComboBoxEntry which has one column of text (a simple list), and appropriate methods for setting and getting the text.
class ComboBoxText
This is a specialisation of the ComboBox which has one column of text (a simple list), and appropriate methods for setting and getting the text.
class ComboDropDown
The dropdown list of a Combo.
class ComboDropDownItem
An item in a ComboDropDownList.
class Container
Abstract container class.
class Curve
Allows direct editing of a curve.
class Dialog
Create popup windows.
class DrawingArea
A widget for custom user interface elements.
class Editable
Base class for text-editing widgets.
class Entry
A single line text entry field.
class EntryCompletion
Completion functionality for Gtk::Entry.
class EventBox
Event capturing box.
class Expander
A container which can hide its child.
class FileChooser
Gtk::FileChooser is an interface that can be implemented by file selection widgets.
class FileChooserButton
A button to launch a file chooser dialog.
class FileChooserDialog
Convenient file chooser window.
class FileChooserError
Exception class for Gdk::FileChooser errors.
class FileChooserWidget
File chooser widget that can be embedded in other widgets.
class FileFilter
A filter for selecting a file subset.
class FileSelection
Prompt the user for a file or directory name.
class Fixed
A container which allows you to position widgets at fixed coordinates.
class FontButton
A button to launch a font selection dialog.
class FontSelection
A widget for selecting fonts.
class FontSelectionDialog
A dialog box for selecting fonts.
class Frame
A Gtk::Bin with a decorative frame and optional label.
class GammaCurve
A subclass of Gtk::Curve for editing gamma curves.
class HandleBox
A widget for detachable window portions.
class HBox
Horizontal Box for laying widgets in a horizontal row.
class HButtonBox
A container for arranging buttons horizontally.
class HPaned
The Gtk::HPaned widget is a container widget with two children arranged horizontally.
class HRuler
Horizontal Ruler.
class HScale
A horizontal slider for selecting values.
class HScrollbar
A horizontal scrollbar.
class HSeparator
Horizontal line widget.
class IconFactory
class IconInfo
class IconSet
class IconSize
Represents registered icon sizes.
class IconSource
class IconTheme
class IconThemeError
Exception class for Gdk::IconTheme errors.
class IconView
The IconView provides an alternative view of a list model.
class Image
A widget displaying an image.
class ImageMenuItem
A menu item with an icon.
class InputDialog
class Invisible
This widget is used internally in GTK+, and is probably not useful for application developers.
class Item
This class should be considered as a virtual base class.
class Label
A widget that displays a small to medium amount of text.
class Layout
Infinite scrollable area containing child widgets and/or custom drawing.
class LinkButton
Create buttons bound to a URL.
class ListStore
Thist is a list model for use with a Gtk::TreeView widget.
class ListViewText
A simple listbox which presents some lines of information in columns and lets the user select some of them.
class Main
Main application class Every application must have one of these objects.
class Menu
A drop-down menu consisting of Gtk::MenuItem objects which can be navigated and activated by the user to perform application functions.
class MenuBar
A standard menu bar which usually holds Gtk::Menu submenu items.
class MenuItem
Child item for menus.
class MenuShell
The abstract base class for Gtk::Menu and Gtk::MenuBar.
class MenuToolButton
A Gtk::ToolItem containing a toggle button.
class MessageDialog
Convenient message window.
class Misc
A base class for widgets with alignments and padding.
class Notebook
Container which shows one of its children at a time, in tabbed windows.
class Object
Gtk::Object is the base class for all widgets, and for a few non-widget objects such as Gtk::Adjustment.
class OptionMenu
A widget used to choose from a list of valid choices.
class PageSetup
A PageSetup object stores the page size, orientation and margins.
class PageSetupUnixDialog
PageSetupUnixDialog implements a page setup dialog for platforms which don't provide a native page setup dialog, like Unix.
class Paned
This is the base class for widgets with two panes, arranged either horizontally (Gtk::HPaned) or vertically (Gtk::VPaned).
class PaperSize
PaperSize handles paper sizes.
class Plug
class PrintContext
A PrintContext encapsulates context information that is required when drawing pages for printing, such as the cairo context and important parameters like page size and resolution.
class Printer
A Printer object represents a printer.
class PrintError
class PrintJob
A PrintJob object represents a job that is sent to a printer.
class PrintOperation
PrintOperation is the high-level, portable printing API.
class PrintOperationPreview
class PrintSettings
A PrintSettings object represents the settings of a print dialog in a system-independent way.
class PrintUnixDialog
PrintUnixDialog implements a print dialog for platforms which don't provide a native print dialog, like Unix.
class ProgressBar
A widget which indicates progress visually.
class RadioAction
An action of which only one in a group can be active.
class RadioButton
A single radio button performs the same basic function as a Gtk::CheckButton, as its position in the object hierarchy reflects.
class RadioButtonGroup
RadioButtonGroup identifier for RadioButtons To set up this RadioButtonGroup, construct a RadioButtonGroup and then pass it to the constructor of all radio items.
class RadioMenuItem
A CheckMenuItem that belongs to a group.
class RadioToolButton
A toolbar item that contains a radio button.
class Range
Base class for widgets which visualize an adjustment.
class RC
class RcStyle
class RecentAction
An action of which represents a list of recently used files.
class RecentChooser
RecentChooser is an interface that can be implemented by widgets displaying the list of recently used files.
class RecentChooserDialog
RecentChooserDialog is a dialog box suitable for displaying the recently used documents.
class RecentChooserError
Exception class for Gtk::RecentChooser errors.
class RecentChooserMenu
RecentChooserMenu is a widget suitable for displaying recently used files inside a menu.
class RecentChooserWidget
RecentChooserWidget is a widget suitable for selecting recently used files.
class RecentFilter
RecentFilter can be used to restrict the files being shown in a RecentChooser.
class RecentInfo
Contains informations found when looking up an entry of the recently used files list.
class RecentManager
RecentManager provides a facility for adding, removing and looking up recently used files.
class RecentManagerError
Exception class for Gtk::RecentManager errors.
class Ruler
Base class for horizontal or vertical rulers.
class Scale
Abstract base clase for Gtk::HScale and Gtk::VScale.
class ScaleButton
A button which pops up a scale widget.
class Scrollbar
The Gtk::Scrollbar widget is an abstract base class for Gtk::HScrollbar and Gtk::VScrollbar.
class ScrolledWindow
Adds scrollbars to its child widget.
class SelectionData
class Separator
Separator base class.
class SeparatorMenuItem
A separator used to group items within a menu.
class SeparatorToolItem
A toolbar item that separates groups of other toolbar items.
class Settings
Sharing settings between applications.
class SizeGroup
Gtk::SizeGroup provides a mechanism for grouping a number of widgets together so they all request the same amount of space.
class Socket
Container for widgets from other processes.
class SpinButton
numeric Entry with up/down buttons Slightly misnamed, this should be called a SpinEntry.
class Statusbar
Text status indicator This widget is used to display status information.
class StatusIcon
The "system tray" or notification area is normally used for transient icons that indicate some special state.
class StockID
See also Gtk::BuiltinStockID.
class StockItem
class Style
class Table
Pack widgets in regular patterns.
class TargetEntry
class TargetList
class TearoffMenuItem
A special Gtk::MenuItem which is used to tear off and reattach its menu.
class TextAttributes
class TextBuffer
Multi-line attributed text that can be displayed by one or more Gtk::TextView widgets.
class TextChildAnchor
A TextChildAnchor is a spot in the buffer where child widgets can be "anchored" (inserted inline, as if they were characters).
class TextIter
Typefed as Gtk::TextBuffer::iterator.
class TextMark
Typedefed as Gtk::TextBuffer::Mark.
class TextTag
Typedefed as Gtk::TextBuffer::Tag.
class TextTagTable
Typedefed as Gtk::TextBuffer::TagTable.
class TextView
Multi-line text editing widget.
class ToggleAction
An action which can be toggled between two states.
class ToggleButton
A Gtk::ToggleButton will remain 'pressed-in' when clicked.
class ToggleToolButton
A Gtk::ToolItem containing a toggle button.
class Toolbar
Bars of buttons and other widgets.
class ToolButton
A Gtk::ToolItem subclass that displays buttons.
class ToolItem
class ToolShell
A base class for containers containing ToolItem widgets.
class Tooltip
Add tips to your widgets.
class Tooltips
Tooltips are the messages that appear next to a widget when the mouse pointer is held over it for a short amount of time.
class TreeDragDest
class TreeDragSource
class TreeIter
A Gtk::TreeModel::iterator is a reference to a specific node on a specific model.
class TreeIterBase
class TreeModel
This class defines a generic tree interface for use by the Gtk::TreeView widget.
class TreeModelColumn
A Gtk::TreeModelColumn describes the C++ type of the data in a model column, and identifies that column in the model.
class TreeModelColumnBase
Base class of TreeModelColumn templates.
class TreeModelColumnRecord
Typedefed as TreeModel::ColumnRecord.
class TreeModelFilter
class TreeModelSort
A wrapper which makes an underlying Gtk::TreeModel sortable.
class TreeNodeChildren
typedefed as TreeModel::Children.
class TreePath
A path is essentially a potential node.
class TreeRow
Typedefed as TreeModel::Row.
class TreeRowReference
Typedefed as Gtk::TreeModel::RowReference.
class TreeSelection
Typedefed as Gtk::TreeView::Selection.
class TreeSortable
class TreeStore
class TreeValueProxy
class TreeView
The TreeView widget displays the model (Gtk::TreeModel) data and allows the user to interact with it.
class TreeViewColumn
Typedefed as Gtk::TreeView::Column.
class UIManager
Constructing menus and toolbars from an XML description.
class VBox
Vertical Box for laying widgets in a vertical row.
class VButtonBox
A container for arranging buttons vertically.
class Viewport
An adapter which makes widgets scrollable.
class VolumeButton
A button which pops up a volume control.
class VPaned
The Gtk::VPaned widget is a container widget with two children arranged horizontally.
class VRuler
Vertical Ruler.
class VScale
A vertical slider for selecting values.
class VScrollbar
A vertical scrollbar.
class VSeparator
Vertical line widget.
class Widget
Abstract Widget (Base class for all widgets).
class Window
Toplevel Window This represents all widgets which are physical windows controlled by the window manager.
class WindowGroup
Limit the effect of grabs.
Typedefs
typedef Gdk::Rectangle Allocation
typedef Glib::ArrayHandle
< TargetEntry,
TargetEntry_Traits > ArrayHandle_TargetEntry
typedef GtkBorder Border
typedef GtkRequisition Requisition
typedef sigc::slot< void,
const Glib::RefPtr<PageSetup >&> SlotPrintSetupDone
For example, void on_setup_done(const Glib::RefPtr<PageSetup>& page_setup);.
Enumerations
enum { BUTTONBOX_DEFAULT = -1 }
enum { INPUT_ERROR = -1 }
enum AccelFlags {
ACCEL_VISIBLE = 1 << 0,
ACCEL_LOCKED = 1 << 1,
ACCEL_MASK = 0x07
}
enum AlignmentEnum {
ALIGN_LEFT,
ALIGN_CENTER,
ALIGN_RIGHT,
ALIGN_TOP,
ALIGN_BOTTOM
}
Methods are overriden so you can use these simple enums, or floats for more precision.
enum AnchorType {
ANCHOR_CENTER,
ANCHOR_NORTH,
ANCHOR_NORTH_WEST,
ANCHOR_NORTH_EAST,
ANCHOR_SOUTH,
ANCHOR_SOUTH_WEST,
ANCHOR_SOUTH_EAST,
ANCHOR_WEST,
ANCHOR_EAST,
ANCHOR_N = ANCHOR_NORTH,
ANCHOR_NW = ANCHOR_NORTH_WEST,
ANCHOR_NE = ANCHOR_NORTH_EAST,
ANCHOR_S = ANCHOR_SOUTH,
ANCHOR_SW = ANCHOR_SOUTH_WEST,
ANCHOR_SE = ANCHOR_SOUTH_EAST,
ANCHOR_W = ANCHOR_WEST,
ANCHOR_E = ANCHOR_EAST
}
enum ArrowType {
ARROW_UP,
ARROW_DOWN,
ARROW_LEFT,
ARROW_RIGHT,
ARROW_NONE
}
Used to indicate the direction in which a Gtk::Arrow should point.
enum AssistantPageType {
ASSISTANT_PAGE_CONTENT,
ASSISTANT_PAGE_INTRO,
ASSISTANT_PAGE_CONFIRM,
ASSISTANT_PAGE_SUMMARY,
ASSISTANT_PAGE_PROGRESS
}
enum AttachOptions {
EXPAND = 1 << 0,
SHRINK = 1 << 1,
FILL = 1 << 2
}
Denotes the expansion properties that a widget will have when it (or its parent) is resized.
enum BuiltinIconSize {
ICON_SIZE_INVALID,
ICON_SIZE_MENU,
ICON_SIZE_SMALL_TOOLBAR,
ICON_SIZE_LARGE_TOOLBAR,
ICON_SIZE_BUTTON,
ICON_SIZE_DND,
ICON_SIZE_DIALOG
}
enum ButtonBoxStyle {
BUTTONBOX_DEFAULT_STYLE,
BUTTONBOX_SPREAD,
BUTTONBOX_EDGE,
BUTTONBOX_START,
BUTTONBOX_END,
BUTTONBOX_CENTER
}
enum ButtonsType {
BUTTONS_NONE,
BUTTONS_OK,
BUTTONS_CLOSE,
BUTTONS_CANCEL,
BUTTONS_YES_NO,
BUTTONS_OK_CANCEL
}
enum CalendarDisplayOptions {
CALENDAR_SHOW_HEADING = 1 << 0,
CALENDAR_SHOW_DAY_NAMES = 1 << 1,
CALENDAR_NO_MONTH_CHANGE = 1 << 2,
CALENDAR_SHOW_WEEK_NUMBERS = 1 << 3,
CALENDAR_WEEK_START_MONDAY = 1 << 4,
CALENDAR_SHOW_DETAILS = 1 << 5
}
enum CellRendererMode {
CELL_RENDERER_MODE_INERT,
CELL_RENDERER_MODE_ACTIVATABLE,
CELL_RENDERER_MODE_EDITABLE
}
enum CellRendererState {
CELL_RENDERER_SELECTED = 1 << 0,
CELL_RENDERER_PRELIT = 1 << 1,
CELL_RENDERER_INSENSITIVE = 1 << 2,
CELL_RENDERER_SORTED = 1 << 3,
CELL_RENDERER_FOCUSED = 1 << 4
}
enum CornerType {
CORNER_TOP_LEFT,
CORNER_BOTTOM_LEFT,
CORNER_TOP_RIGHT,
CORNER_BOTTOM_RIGHT
}
enum CurveType {
CURVE_TYPE_LINEAR,
CURVE_TYPE_SPLINE,
CURVE_TYPE_FREE
}
enum DeleteType {
DELETE_CHARS,
DELETE_WORDS,
DELETE_DISPLAY_LINES,
DELETE_DISPLAY_LINE_ENDS,
DELETE_PARAGRAPH_ENDS,
DELETE_PARAGRAPHS,
DELETE_WHITESPACE
}
enum DestDefaults {
DEST_DEFAULT_MOTION = 1 << 0,
DEST_DEFAULT_HIGHLIGHT = 1 << 1,
DEST_DEFAULT_DROP = 1 << 2,
DEST_DEFAULT_ALL = 0x07
}
enum DirectionType {
DIR_TAB_FORWARD,
DIR_TAB_BACKWARD,
DIR_UP,
DIR_DOWN,
DIR_LEFT,
DIR_RIGHT
}
enum DragResult {
DRAG_RESULT_SUCCESS,
DRAG_RESULT_NO_TARGET,
DRAG_RESULT_USER_CANCELLED,
DRAG_RESULT_TIMEOUT_EXPIRED,
DRAG_RESULT_GRAB_BROKEN,
DRAG_RESULT_ERROR
}
enum ExpanderStyle {
EXPANDER_COLLAPSED,
EXPANDER_SEMI_COLLAPSED,
EXPANDER_SEMI_EXPANDED,
EXPANDER_EXPANDED
}
enum FileChooserAction {
FILE_CHOOSER_ACTION_OPEN,
FILE_CHOOSER_ACTION_SAVE,
FILE_CHOOSER_ACTION_SELECT_FOLDER,
FILE_CHOOSER_ACTION_CREATE_FOLDER
}
enum FileChooserConfirmation {
FILE_CHOOSER_CONFIRMATION_CONFIRM,
FILE_CHOOSER_CONFIRMATION_ACCEPT_FILENAME,
FILE_CHOOSER_CONFIRMATION_SELECT_AGAIN
}
enum FileFilterFlags {
FILE_FILTER_FILENAME = 1 << 0,
FILE_FILTER_URI = 1 << 1,
FILE_FILTER_DISPLAY_NAME = 1 << 2,
FILE_FILTER_MIME_TYPE = 1 << 3
}
enum IconLookupFlags {
ICON_LOOKUP_NO_SVG = 1 << 0,
ICON_LOOKUP_FORCE_SVG = 1 << 1,
ICON_LOOKUP_USE_BUILTIN = 1 << 2,
ICON_LOOKUP_GENERIC_FALLBACK = 1 << 3,
ICON_LOOKUP_FORCE_SIZE = 1 << 4
}
enum IconViewDropPosition {
ICON_VIEW_NO_DROP,
ICON_VIEW_DROP_INTO,
ICON_VIEW_DROP_LEFT,
ICON_VIEW_DROP_RIGHT,
ICON_VIEW_DROP_ABOVE,
ICON_VIEW_DROP_BELOW
}
enum ImageType {
IMAGE_EMPTY,
IMAGE_PIXMAP,
IMAGE_IMAGE,
IMAGE_PIXBUF,
IMAGE_STOCK,
IMAGE_ICON_SET,
IMAGE_ANIMATION,
IMAGE_ICON_NAME,
IMAGE_GICON
}
enum Justification {
JUSTIFY_LEFT,
JUSTIFY_RIGHT,
JUSTIFY_CENTER,
JUSTIFY_FILL
}
enum MenuDirectionType {
MENU_DIR_PARENT,
MENU_DIR_CHILD,
MENU_DIR_NEXT,
MENU_DIR_PREV
}
enum MessageType {
MESSAGE_INFO,
MESSAGE_WARNING,
MESSAGE_QUESTION,
MESSAGE_ERROR,
MESSAGE_OTHER
}
enum MetricType {
PIXELS,
INCHES,
CENTIMETERS
}
enum MovementStep {
MOVEMENT_LOGICAL_POSITIONS,
MOVEMENT_VISUAL_POSITIONS,
MOVEMENT_WORDS,
MOVEMENT_DISPLAY_LINES,
MOVEMENT_DISPLAY_LINE_ENDS,
MOVEMENT_PARAGRAPHS,
MOVEMENT_PARAGRAPH_ENDS,
MOVEMENT_PAGES,
MOVEMENT_BUFFER_ENDS,
MOVEMENT_HORIZONTAL_PAGES
}
enum NotebookTab {
NOTEBOOK_TAB_FIRST,
NOTEBOOK_TAB_LAST
}
enum NumberUpLayout {
NUMBER_UP_LAYOUT_LEFT_TO_RIGHT_TOP_TO_BOTTOM,
NUMBER_UP_LAYOUT_LEFT_TO_RIGHT_BOTTOM_TO_TOP,
NUMBER_UP_LAYOUT_RIGHT_TO_LEFT_TOP_TO_BOTTOM,
NUMBER_UP_LAYOUT_RIGHT_TO_LEFT_BOTTOM_TO_TOP,
NUMBER_UP_LAYOUT_TOP_TO_BOTTOM_LEFT_TO_RIGHT,
NUMBER_UP_LAYOUT_TOP_TO_BOTTOM_RIGHT_TO_LEFT,
NUMBER_UP_LAYOUT_BOTTOM_TO_TOP_LEFT_TO_RIGHT,
NUMBER_UP_LAYOUT_BOTTOM_TO_TOP_RIGHT_TO_LEFT
}
enum Orientation {
ORIENTATION_HORIZONTAL,
ORIENTATION_VERTICAL
}
enum PackOptions {
PACK_SHRINK,
PACK_EXPAND_PADDING,
PACK_EXPAND_WIDGET
}
Packing options for adding child widgets to a Box with pack_start() and pack_end().
enum PackType {
PACK_START,
PACK_END
}
enum PageOrientation {
PAGE_ORIENTATION_PORTRAIT,
PAGE_ORIENTATION_LANDSCAPE,
PAGE_ORIENTATION_REVERSE_PORTRAIT,
PAGE_ORIENTATION_REVERSE_LANDSCAPE
}
enum PageSet {
PAGE_SET_ALL,
PAGE_SET_EVEN,
PAGE_SET_ODD
}
enum PathPriorityType {
PATH_PRIO_LOWEST = 0,
PATH_PRIO_GTK = 4,
PATH_PRIO_APPLICATION = 8,
PATH_PRIO_THEME = 10,
PATH_PRIO_RC = 12,
PATH_PRIO_HIGHEST = 15
}
enum PathType {
PATH_WIDGET,
PATH_WIDGET_CLASS,
PATH_CLASS
}
enum PolicyType {
POLICY_ALWAYS,
POLICY_AUTOMATIC,
POLICY_NEVER
}
enum PositionType {
POS_LEFT,
POS_RIGHT,
POS_TOP,
POS_BOTTOM
}
enum PrintCapabilities {
PRINT_CAPABILITY_PAGE_SET = 1 << 0,
PRINT_CAPABILITY_COPIES = 1 << 1,
PRINT_CAPABILITY_COLLATE = 1 << 2,
PRINT_CAPABILITY_REVERSE = 1 << 3,
PRINT_CAPABILITY_SCALE = 1 << 4,
PRINT_CAPABILITY_GENERATE_PDF = 1 << 5,
PRINT_CAPABILITY_GENERATE_PS = 1 << 6,
PRINT_CAPABILITY_PREVIEW = 1 << 7,
PRINT_CAPABILITY_NUMBER_UP = 1 << 8,
PRINT_CAPABILITY_NUMBER_UP_LAYOUT = 1 << 9
}
enum PrintDuplex {
PRINT_DUPLEX_SIMPLEX,
PRINT_DUPLEX_HORIZONTAL,
PRINT_DUPLEX_VERTICAL
}
enum PrintOperationAction {
PRINT_OPERATION_ACTION_PRINT_DIALOG,
PRINT_OPERATION_ACTION_PRINT,
PRINT_OPERATION_ACTION_PREVIEW,
PRINT_OPERATION_ACTION_EXPORT
}
enum PrintOperationResult {
PRINT_OPERATION_RESULT_ERROR,
PRINT_OPERATION_RESULT_APPLY,
PRINT_OPERATION_RESULT_CANCEL,
PRINT_OPERATION_RESULT_IN_PROGRESS
}
enum PrintPages {
PRINT_PAGES_ALL,
PRINT_PAGES_CURRENT,
PRINT_PAGES_RANGES
}
enum PrintQuality {
PRINT_QUALITY_LOW,
PRINT_QUALITY_NORMAL,
PRINT_QUALITY_HIGH,
PRINT_QUALITY_DRAFT
}
enum PrintStatus {
PRINT_STATUS_INITIAL,
PRINT_STATUS_PREPARING,
PRINT_STATUS_GENERATING_DATA,
PRINT_STATUS_SENDING_DATA,
PRINT_STATUS_PENDING,
PRINT_STATUS_PENDING_ISSUE,
PRINT_STATUS_PRINTING,
PRINT_STATUS_FINISHED,
PRINT_STATUS_FINISHED_ABORTED
}
enum ProgressBarOrientation {
PROGRESS_LEFT_TO_RIGHT,
PROGRESS_RIGHT_TO_LEFT,
PROGRESS_BOTTOM_TO_TOP,
PROGRESS_TOP_TO_BOTTOM
}
enum ProgressBarStyle {
PROGRESS_CONTINUOUS,
PROGRESS_DISCRETE
}
enum RcFlags {
RC_FG = 1 << 0,
RC_BG = 1 << 1,
RC_TEXT = 1 << 2,
RC_BASE = 1 << 3
}
enum RecentFilterFlags {
RECENT_FILTER_URI = 1 << 0,
RECENT_FILTER_DISPLAY_NAME = 1 << 1,
RECENT_FILTER_MIME_TYPE = 1 << 2,
RECENT_FILTER_APPLICATION = 1 << 3,
RECENT_FILTER_GROUP = 1 << 4,
RECENT_FILTER_AGE = 1 << 5
}
enum RecentSortType {
RECENT_SORT_NONE,
RECENT_SORT_MRU,
RECENT_SORT_LRU,
RECENT_SORT_CUSTOM
}
enum ReliefStyle {
RELIEF_NORMAL,
RELIEF_HALF,
RELIEF_NONE
}
enum ResizeMode {
RESIZE_PARENT,
RESIZE_QUEUE,
RESIZE_IMMEDIATE
}
enum ResponseType {
RESPONSE_NONE = -1,
RESPONSE_REJECT = -2,
RESPONSE_ACCEPT = -3,
RESPONSE_DELETE_EVENT = -4,
RESPONSE_OK = -5,
RESPONSE_CANCEL = -6,
RESPONSE_CLOSE = -7,
RESPONSE_YES = -8,
RESPONSE_NO = -9,
RESPONSE_APPLY = -10,
RESPONSE_HELP = -11
}
enum ScrollType {
SCROLL_NONE,
SCROLL_JUMP,
SCROLL_STEP_BACKWARD,
SCROLL_STEP_FORWARD,
SCROLL_PAGE_BACKWARD,
SCROLL_PAGE_FORWARD,
SCROLL_STEP_UP,
SCROLL_STEP_DOWN,
SCROLL_PAGE_UP,
SCROLL_PAGE_DOWN,
SCROLL_STEP_LEFT,
SCROLL_STEP_RIGHT,
SCROLL_PAGE_LEFT,
SCROLL_PAGE_RIGHT,
SCROLL_START,
SCROLL_END
}
enum SelectionMode {
SELECTION_NONE,
SELECTION_SINGLE,
SELECTION_BROWSE,
SELECTION_MULTIPLE,
SELECTION_EXTENDED = SELECTION_MULTIPLE
}
enum SensitivityType {
SENSITIVITY_AUTO,
SENSITIVITY_ON,
SENSITIVITY_OFF
}
enum ShadowType {
SHADOW_NONE,
SHADOW_IN,
SHADOW_OUT,
SHADOW_ETCHED_IN,
SHADOW_ETCHED_OUT
}
enum SizeGroupMode {
SIZE_GROUP_NONE,
SIZE_GROUP_HORIZONTAL,
SIZE_GROUP_VERTICAL,
SIZE_GROUP_BOTH
}
enum SortType {
SORT_ASCENDING,
SORT_DESCENDING
}
enum SpinButtonUpdatePolicy {
UPDATE_ALWAYS,
UPDATE_IF_VALID
}
enum SpinType {
SPIN_STEP_FORWARD,
SPIN_STEP_BACKWARD,
SPIN_PAGE_FORWARD,
SPIN_PAGE_BACKWARD,
SPIN_HOME,
SPIN_END,
SPIN_USER_DEFINED
}
enum StateType {
STATE_NORMAL,
STATE_ACTIVE,
STATE_PRELIGHT,
STATE_SELECTED,
STATE_INSENSITIVE
}
enum TargetFlags {
TARGET_SAME_APP = 1 << 0,
TARGET_SAME_WIDGET = 1 << 1,
TARGET_OTHER_APP = 1 << 2,
TARGET_OTHER_WIDGET = 1 << 3
}
enum TextDirection {
TEXT_DIR_NONE,
TEXT_DIR_LTR,
TEXT_DIR_RTL
}
enum TextSearchFlags {
TEXT_SEARCH_VISIBLE_ONLY = 1 << 0,
TEXT_SEARCH_TEXT_ONLY = 1 << 1
}
enum TextWindowType {
TEXT_WINDOW_PRIVATE,
TEXT_WINDOW_WIDGET,
TEXT_WINDOW_TEXT,
TEXT_WINDOW_LEFT,
TEXT_WINDOW_RIGHT,
TEXT_WINDOW_TOP,
TEXT_WINDOW_BOTTOM
}
enum ToolbarStyle {
TOOLBAR_ICONS,
TOOLBAR_TEXT,
TOOLBAR_BOTH,
TOOLBAR_BOTH_HORIZ
}
enum TreeModelFlags {
TREE_MODEL_ITERS_PERSIST = 1 << 0,
TREE_MODEL_LIST_ONLY = 1 << 1
}
enum TreeViewColumnSizing {
TREE_VIEW_COLUMN_GROW_ONLY,
TREE_VIEW_COLUMN_AUTOSIZE,
TREE_VIEW_COLUMN_FIXED
}
enum TreeViewDropPosition {
TREE_VIEW_DROP_BEFORE,
TREE_VIEW_DROP_AFTER,
TREE_VIEW_DROP_INTO_OR_BEFORE,
TREE_VIEW_DROP_INTO_OR_AFTER
}
enum TreeViewGridLines {
TREE_VIEW_GRID_LINES_NONE,
TREE_VIEW_GRID_LINES_HORIZONTAL,
TREE_VIEW_GRID_LINES_VERTICAL,
TREE_VIEW_GRID_LINES_BOTH
}
enum UIManagerItemType {
UI_MANAGER_AUTO = 0,
UI_MANAGER_MENUBAR = 1 << 0,
UI_MANAGER_MENU = 1 << 1,
UI_MANAGER_TOOLBAR = 1 << 2,
UI_MANAGER_PLACEHOLDER = 1 << 3,
UI_MANAGER_POPUP = 1 << 4,
UI_MANAGER_MENUITEM = 1 << 5,
UI_MANAGER_TOOLITEM = 1 << 6,
UI_MANAGER_SEPARATOR = 1 << 7,
UI_MANAGER_ACCELERATOR = 1 << 8
}
enum Unit {
UNIT_PIXEL,
UNIT_POINTS,
UNIT_INCH,
UNIT_MM
}
enum UpdateType {
UPDATE_CONTINUOUS,
UPDATE_DISCONTINUOUS,
UPDATE_DELAYED
}
enum Visibility {
VISIBILITY_NONE,
VISIBILITY_PARTIAL,
VISIBILITY_FULL
}
enum WidgetFlags {
TOPLEVEL = 1 << 4,
NO_WINDOW = 1 << 5,
REALIZED = 1 << 6,
MAPPED = 1 << 7,
VISIBLE = 1 << 8,
SENSITIVE = 1 << 9,
PARENT_SENSITIVE = 1 << 10,
CAN_FOCUS = 1 << 11,
HAS_FOCUS = 1 << 12,
CAN_DEFAULT = 1 << 13,
HAS_DEFAULT = 1 << 14,
HAS_GRAB = 1 << 15,
RC_STYLE = 1 << 16,
COMPOSITE_CHILD = 1 << 17,
NO_REPARENT = 1 << 18,
APP_PAINTABLE = 1 << 19,
RECEIVES_DEFAULT = 1 << 20,
DOUBLE_BUFFERED = 1 << 21,
NO_SHOW_ALL = 1 << 22
}
enum WidgetHelpType {
WIDGET_HELP_TOOLTIP,
WIDGET_HELP_WHATS_THIS
}
enum WindowPosition {
WIN_POS_NONE,
WIN_POS_CENTER,
WIN_POS_MOUSE,
WIN_POS_CENTER_ALWAYS,
WIN_POS_CENTER_ON_PARENT
}
enum WindowType {
WINDOW_TOPLEVEL,
WINDOW_POPUP
}
enum WrapMode {
WRAP_NONE,
WRAP_CHAR,
WRAP_WORD,
WRAP_WORD_CHAR
}
Functions
template<class T >
T* manage (T* obj)
Mark a Gtk::Object as owned by its parent container widget, so you don't need to delete it manually.
WidgetFlags operator& (WidgetFlags lhs, WidgetFlags rhs)
DestDefaults operator& (DestDefaults lhs, DestDefaults rhs)
UIManagerItemType operator& (UIManagerItemType lhs, UIManagerItemType rhs)
TreeModelFlags operator& (TreeModelFlags lhs, TreeModelFlags rhs)
TextSearchFlags operator& (TextSearchFlags lhs, TextSearchFlags rhs)
RecentFilterFlags operator& (RecentFilterFlags lhs, RecentFilterFlags rhs)
RcFlags operator& (RcFlags lhs, RcFlags rhs)
PrintCapabilities operator& (PrintCapabilities lhs, PrintCapabilities rhs)
IconLookupFlags operator& (IconLookupFlags lhs, IconLookupFlags rhs)
FileFilterFlags operator& (FileFilterFlags lhs, FileFilterFlags rhs)
TargetFlags operator& (TargetFlags lhs, TargetFlags rhs)
AttachOptions operator& (AttachOptions lhs, AttachOptions rhs)
AccelFlags operator& (AccelFlags lhs, AccelFlags rhs)
CellRendererState operator& (CellRendererState lhs, CellRendererState rhs)
CalendarDisplayOptions operator& (CalendarDisplayOptions lhs, CalendarDisplayOptions rhs)
WidgetFlags& operator&= (WidgetFlags& lhs, WidgetFlags rhs)
DestDefaults& operator&= (DestDefaults& lhs, DestDefaults rhs)
UIManagerItemType& operator&= (UIManagerItemType& lhs, UIManagerItemType rhs)
TreeModelFlags& operator&= (TreeModelFlags& lhs, TreeModelFlags rhs)
TextSearchFlags& operator&= (TextSearchFlags& lhs, TextSearchFlags rhs)
RecentFilterFlags& operator&= (RecentFilterFlags& lhs, RecentFilterFlags rhs)
RcFlags& operator&= (RcFlags& lhs, RcFlags rhs)
PrintCapabilities& operator&= (PrintCapabilities& lhs, PrintCapabilities rhs)
IconLookupFlags& operator&= (IconLookupFlags& lhs, IconLookupFlags rhs)
FileFilterFlags& operator&= (FileFilterFlags& lhs, FileFilterFlags rhs)
TargetFlags& operator&= (TargetFlags& lhs, TargetFlags rhs)
AttachOptions& operator&= (AttachOptions& lhs, AttachOptions rhs)
AccelFlags& operator&= (AccelFlags& lhs, AccelFlags rhs)
CellRendererState& operator&= (CellRendererState& lhs, CellRendererState rhs)
CalendarDisplayOptions& operator&= (CalendarDisplayOptions& lhs, CalendarDisplayOptions rhs)
WidgetFlags operator^ (WidgetFlags lhs, WidgetFlags rhs)
DestDefaults operator^ (DestDefaults lhs, DestDefaults rhs)
UIManagerItemType operator^ (UIManagerItemType lhs, UIManagerItemType rhs)
TreeModelFlags operator^ (TreeModelFlags lhs, TreeModelFlags rhs)
TextSearchFlags operator^ (TextSearchFlags lhs, TextSearchFlags rhs)
RecentFilterFlags operator^ (RecentFilterFlags lhs, RecentFilterFlags rhs)
RcFlags operator^ (RcFlags lhs, RcFlags rhs)
PrintCapabilities operator^ (PrintCapabilities lhs, PrintCapabilities rhs)
IconLookupFlags operator^ (IconLookupFlags lhs, IconLookupFlags rhs)
FileFilterFlags operator^ (FileFilterFlags lhs, FileFilterFlags rhs)
TargetFlags operator^ (TargetFlags lhs, TargetFlags rhs)
AttachOptions operator^ (AttachOptions lhs, AttachOptions rhs)
AccelFlags operator^ (AccelFlags lhs, AccelFlags rhs)
CellRendererState operator^ (CellRendererState lhs, CellRendererState rhs)
CalendarDisplayOptions operator^ (CalendarDisplayOptions lhs, CalendarDisplayOptions rhs)
WidgetFlags& operator^= (WidgetFlags& lhs, WidgetFlags rhs)
DestDefaults& operator^= (DestDefaults& lhs, DestDefaults rhs)
UIManagerItemType& operator^= (UIManagerItemType& lhs, UIManagerItemType rhs)
TreeModelFlags& operator^= (TreeModelFlags& lhs, TreeModelFlags rhs)
TextSearchFlags& operator^= (TextSearchFlags& lhs, TextSearchFlags rhs)
RecentFilterFlags& operator^= (RecentFilterFlags& lhs, RecentFilterFlags rhs)
RcFlags& operator^= (RcFlags& lhs, RcFlags rhs)
PrintCapabilities& operator^= (PrintCapabilities& lhs, PrintCapabilities rhs)
IconLookupFlags& operator^= (IconLookupFlags& lhs, IconLookupFlags rhs)
FileFilterFlags& operator^= (FileFilterFlags& lhs, FileFilterFlags rhs)
TargetFlags& operator^= (TargetFlags& lhs, TargetFlags rhs)
AttachOptions& operator^= (AttachOptions& lhs, AttachOptions rhs)
AccelFlags& operator^= (AccelFlags& lhs, AccelFlags rhs)
CellRendererState& operator^= (CellRendererState& lhs, CellRendererState rhs)
CalendarDisplayOptions& operator^= (CalendarDisplayOptions& lhs, CalendarDisplayOptions rhs)
WidgetFlags operator| (WidgetFlags lhs, WidgetFlags rhs)
DestDefaults operator| (DestDefaults lhs, DestDefaults rhs)
UIManagerItemType operator| (UIManagerItemType lhs, UIManagerItemType rhs)
TreeModelFlags operator| (TreeModelFlags lhs, TreeModelFlags rhs)
TextSearchFlags operator| (TextSearchFlags lhs, TextSearchFlags rhs)
RecentFilterFlags operator| (RecentFilterFlags lhs, RecentFilterFlags rhs)
RcFlags operator| (RcFlags lhs, RcFlags rhs)
PrintCapabilities operator| (PrintCapabilities lhs, PrintCapabilities rhs)
IconLookupFlags operator| (IconLookupFlags lhs, IconLookupFlags rhs)
FileFilterFlags operator| (FileFilterFlags lhs, FileFilterFlags rhs)
TargetFlags operator| (TargetFlags lhs, TargetFlags rhs)
AttachOptions operator| (AttachOptions lhs, AttachOptions rhs)
AccelFlags operator| (AccelFlags lhs, AccelFlags rhs)
CellRendererState operator| (CellRendererState lhs, CellRendererState rhs)
CalendarDisplayOptions operator| (CalendarDisplayOptions lhs, CalendarDisplayOptions rhs)
WidgetFlags& operator|= (WidgetFlags& lhs, WidgetFlags rhs)
DestDefaults& operator|= (DestDefaults& lhs, DestDefaults rhs)
UIManagerItemType& operator|= (UIManagerItemType& lhs, UIManagerItemType rhs)
TreeModelFlags& operator|= (TreeModelFlags& lhs, TreeModelFlags rhs)
TextSearchFlags& operator|= (TextSearchFlags& lhs, TextSearchFlags rhs)
RecentFilterFlags& operator|= (RecentFilterFlags& lhs, RecentFilterFlags rhs)
RcFlags& operator|= (RcFlags& lhs, RcFlags rhs)
PrintCapabilities& operator|= (PrintCapabilities& lhs, PrintCapabilities rhs)
IconLookupFlags& operator|= (IconLookupFlags& lhs, IconLookupFlags rhs)
FileFilterFlags& operator|= (FileFilterFlags& lhs, FileFilterFlags rhs)
TargetFlags& operator|= (TargetFlags& lhs, TargetFlags rhs)
AttachOptions& operator|= (AttachOptions& lhs, AttachOptions rhs)
AccelFlags& operator|= (AccelFlags& lhs, AccelFlags rhs)
CellRendererState& operator|= (CellRendererState& lhs, CellRendererState rhs)
CalendarDisplayOptions& operator|= (CalendarDisplayOptions& lhs, CalendarDisplayOptions rhs)
WidgetFlags operator~ (WidgetFlags flags)
DestDefaults operator~ (DestDefaults flags)
UIManagerItemType operator~ (UIManagerItemType flags)
TreeModelFlags operator~ (TreeModelFlags flags)
TextSearchFlags operator~ (TextSearchFlags flags)
RecentFilterFlags operator~ (RecentFilterFlags flags)
RcFlags operator~ (RcFlags flags)
PrintCapabilities operator~ (PrintCapabilities flags)
IconLookupFlags operator~ (IconLookupFlags flags)
FileFilterFlags operator~ (FileFilterFlags flags)
TargetFlags operator~ (TargetFlags flags)
AttachOptions operator~ (AttachOptions flags)
AccelFlags operator~ (AccelFlags flags)
CellRendererState operator~ (CellRendererState flags)
CalendarDisplayOptions operator~ (CalendarDisplayOptions flags)
Glib::RefPtr<PageSetup> run_page_setup_dialog (Window& parent, const Glib::RefPtr<const PageSetup>& page_setup, const Glib::RefPtr<const PrintSettings>& print_settings)
Runs a page setup dialog, letting the user modify the values from page_setup.
void run_page_setup_dialog_async (Window& parent, const Glib::RefPtr<const PageSetup>& page_setup, const Glib::RefPtr<const PrintSettings>& print_settings, const SlotPrintSetupDone& slot)
Runs a page setup dialog, letting the user modify the values from page_setup.
Variables
const Glib::ustring PAPER_NAME_A3 = "iso_a3"
Common paper names, from PWG 5101.1-2002 PWG: Standard for Media Standardized Names.
const Glib::ustring PAPER_NAME_A4 = "iso_a4"
const Glib::ustring PAPER_NAME_A5 = "iso_a5"
const Glib::ustring PAPER_NAME_B5 = "iso_b5"
const Glib::ustring PAPER_NAME_EXECUTIVE = "na_executive"
const Glib::ustring PAPER_NAME_LEGAL = "na_legal"
const Glib::ustring PAPER_NAME_LETTER = "na_letter"
Typedef Documentation
typedef Gdk::Rectangle Gtk::Allocation
typedef Glib::ArrayHandle<TargetEntry, TargetEntry_Traits> Gtk::ArrayHandle_TargetEntry
typedef GtkBorder Gtk::Border
typedef GtkRequisition Gtk::Requisition
typedef sigc::slot<void, const Glib::RefPtr<PageSetup>&> Gtk::SlotPrintSetupDone
For example, void on_setup_done(const Glib::RefPtr<PageSetup>& page_setup);.
Function Documentation
template <class T > T* Gtk::manage (T * obj) [inline]
Mark a Gtk::Object as owned by its parent container widget, so you don't need to delete it manually.
For instance,
 Gtk::Button* button = Gtk::manage( new Gtk::Button("Hello") );
 vbox.pack_start(*button); //vbox will delete button when vbox is deleted.
Parameters:
obj A Gtk::Object, such as a gtkmm widget.
Returns:
The Gtk::Object passed as the obj parameter.
Referenced by Gtk::TreeView::append_column(), Gtk::TreeView::append_column_editable(), Gtk::TreeView::append_column_numeric(), Gtk::TreeView::insert_column(), Gtk::TreeView::insert_column_editable(), and Gtk::CellLayout::pack_start().
Glib::RefPtr<PageSetup> Gtk::run_page_setup_dialog (Window & parent, const Glib::RefPtr< const PageSetup > & page_setup, const Glib::RefPtr< const PrintSettings > & print_settings)
Runs a page setup dialog, letting the user modify the values from page_setup.
If the user cancels the dialog, the returned PageSetup is identical to that passed in page_setup, otherwise it contains the modifications done in the dialog.
Note that this function may use a recursive mainloop to show the page setup dialog. See run_page_setup_dialog_async() if this is a problem.
Parameters:
parent Transient parent.
page_setup An existing GtkPageSetup.
settings Print settings.
Returns:
A new PageSetup object.
Since:
2.10
void Gtk::run_page_setup_dialog_async (Window & parent, const Glib::RefPtr< const PageSetup > & page_setup, const Glib::RefPtr< const PrintSettings > & print_settings, const SlotPrintSetupDone & slot)
Runs a page setup dialog, letting the user modify the values from page_setup.
In contrast to run_page_setup_dialog(), this function returns after showing the page setup dialog on platforms that support this, and calls the slot from a signal handler for the response signal of the dialog.
Parameters:
parent Transient parent.
page_setup An existing GtkPageSetup.
settings Print settings.
Returns:
A new PageSetup object.
Parameters:
slot
Since:
2.10
Variable Documentation
const Glib::ustring Gtk::PAPER_NAME_A3 = "iso_a3"
Common paper names, from PWG 5101.1-2002 PWG: Standard for Media Standardized Names.
const Glib::ustring Gtk::PAPER_NAME_A4 = "iso_a4"
const Glib::ustring Gtk::PAPER_NAME_A5 = "iso_a5"
const Glib::ustring Gtk::PAPER_NAME_B5 = "iso_b5"
const Glib::ustring Gtk::PAPER_NAME_EXECUTIVE = "na_executive"
const Glib::ustring Gtk::PAPER_NAME_LEGAL = "na_legal"
const Glib::ustring Gtk::PAPER_NAME_LETTER = "na_letter"
Generated for gtkmm 2.4 by Doxygen 1.5.8 © 1997-2001